//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCriminal", ReplyAction="http://tempuri.org/IService1/AddCriminalResponse")]
        string AddCriminal(string criminalName, string type, string age, string gender, string address, string complaint, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCriminal", ReplyAction="http://tempuri.org/IService1/AddCriminalResponse")]
        System.Threading.Tasks.Task<string> AddCriminalAsync(string criminalName, string type, string age, string gender, string address, string complaint, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchItem", ReplyAction="http://tempuri.org/IService1/SearchItemResponse")]
        System.Data.DataSet SearchItem(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchItem", ReplyAction="http://tempuri.org/IService1/SearchItemResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SearchItemAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateItem", ReplyAction="http://tempuri.org/IService1/UpdateItemResponse")]
        string UpdateItem(string criminalName, string type, string age, string gender, string address, string complaint, System.DateTime date, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateItem", ReplyAction="http://tempuri.org/IService1/UpdateItemResponse")]
        System.Threading.Tasks.Task<string> UpdateItemAsync(string criminalName, string type, string age, string gender, string address, string complaint, System.DateTime date, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteItem", ReplyAction="http://tempuri.org/IService1/DeleteItemResponse")]
        string DeleteItem(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteItem", ReplyAction="http://tempuri.org/IService1/DeleteItemResponse")]
        System.Threading.Tasks.Task<string> DeleteItemAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getItems", ReplyAction="http://tempuri.org/IService1/getItemsResponse")]
        System.Data.DataSet getItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getItems", ReplyAction="http://tempuri.org/IService1/getItemsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> getItemsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebClient.ServiceReference1.IService1>, WebClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string AddCriminal(string criminalName, string type, string age, string gender, string address, string complaint, System.DateTime date) {
            return base.Channel.AddCriminal(criminalName, type, age, gender, address, complaint, date);
        }
        
        public System.Threading.Tasks.Task<string> AddCriminalAsync(string criminalName, string type, string age, string gender, string address, string complaint, System.DateTime date) {
            return base.Channel.AddCriminalAsync(criminalName, type, age, gender, address, complaint, date);
        }
        
        public System.Data.DataSet SearchItem(int id) {
            return base.Channel.SearchItem(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SearchItemAsync(int id) {
            return base.Channel.SearchItemAsync(id);
        }
        
        public string UpdateItem(string criminalName, string type, string age, string gender, string address, string complaint, System.DateTime date, int id) {
            return base.Channel.UpdateItem(criminalName, type, age, gender, address, complaint, date, id);
        }
        
        public System.Threading.Tasks.Task<string> UpdateItemAsync(string criminalName, string type, string age, string gender, string address, string complaint, System.DateTime date, int id) {
            return base.Channel.UpdateItemAsync(criminalName, type, age, gender, address, complaint, date, id);
        }
        
        public string DeleteItem(int id) {
            return base.Channel.DeleteItem(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteItemAsync(int id) {
            return base.Channel.DeleteItemAsync(id);
        }
        
        public System.Data.DataSet getItems() {
            return base.Channel.getItems();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getItemsAsync() {
            return base.Channel.getItemsAsync();
        }
    }
}
